version: "3.10"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
  
  app:
    build: 
      context: .
    env_file:
      - .env-non-dev
    container_name: fapp
    command: ['/app/docker/app.sh']
    ports:
      - "9999:8000"
    depends_on:
      - db