"""11 some changes

Revision ID: 55fb4ffe24a7
Revises: fde1f5557dc8
Create Date: 2023-10-22 17:10:54.744946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fb4ffe24a7'
down_revision: Union[str, None] = 'fde1f5557dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_product_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'product', ['product_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_product_id_fkey', 'review', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
